subquery/subql-stellar

- .yarn/versions/13a81a1b.yml
- .yarn/versions/6779a73a.yml
- .yarn/versions/a02f33df.yml
- .yarn/versions/c13714b9.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
New release for subql stellar.
> [release] 20230912

- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/src/project/types.ts
- packages/node/CHANGELOG.md
- packages/node/src/configure/SubqueryProject.ts
- packages/node/src/configure/configure.module.ts
- packages/node/src/stellar/api.service.stellar.spec.ts
Rename `soroban` to `sorobanEndpoint` in network config
> rename soroban to sorobanEndpoint in network config

- .yarn/versions/3279d60e.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
> [release] 20230913

- .yarn/versions/1e13fdde.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
> [release] 20231005

- packages/node/CHANGELOG.md
- packages/node/package.json
New release with performance fix
> [release] 20231011

- .yarn/versions/7bf0c83c.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
> [release] 20231013

- package.json
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
- yarn.lock
> [release] 20231101

- .github/workflows/node-docker.yml
- packages/node/Dockerfile
Update docker CI to build from source
> update docker to build from source - stellar

- .github/workflows/node-docker.yml
- packages/node/Dockerfile
- scripts/build.sh
- tsconfig.json
> [SKIP CI] fix docker publish CI - stellar

- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/yargs.ts
- yarn.lock
> [release] 20231106

- .github/workflows/node-docker.yml
> add context to docker push actions

- packages/node/CHANGELOG.md
- packages/node/package.json
- yarn.lock
> [release] 20231113

- packages/common-stellar/package.json
- packages/common-stellar/src/project/models.ts
- packages/node/package.json
- packages/node/src/indexer/project.service.ts
- packages/node/src/stellar/api.stellar.spec.ts
- packages/node/src/stellar/api.stellar.ts
- packages/node/src/stellar/block.stellar.spec.ts
- packages/node/src/stellar/block.stellar.ts
- packages/node/src/stellar/safe-api.ts
- packages/node/src/stellar/soroban.server.spec.ts
- packages/node/src/stellar/soroban.server.ts
- packages/node/src/stellar/stellar.server.ts
- packages/types/package.json
- packages/types/src/stellar/interfaces.ts
- yarn.lock
> Update soroban client

- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
> [release] 20240122

- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/indexer/indexer.manager.ts
- packages/node/src/meta/meta.service.ts
- packages/node/src/stellar/api.service.stellar.spec.ts
- packages/node/src/stellar/block.stellar.spec.ts
- packages/node/src/stellar/block.stellar.ts
- packages/node/src/stellar/safe-api.ts
- packages/node/src/stellar/soroban.server.spec.ts
- packages/node/src/stellar/soroban.server.ts
- packages/types/CHANGELOG.md
- packages/types/package.json
- packages/types/src/global.ts
- packages/types/src/stellar/interfaces.ts
- yarn.lock
> fix stellar decode issue

- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
> [release] 20240411

- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/configure/SubqueryProject.ts
- packages/node/src/indexer/blockDispatcher/block-dispatcher.service.ts
- packages/node/src/indexer/blockDispatcher/worker-block-dispatcher.service.ts
- packages/node/src/indexer/dynamic-ds.service.ts
- packages/node/src/indexer/indexer.manager.ts
- packages/node/src/indexer/project.service.ts
- packages/node/src/indexer/worker/worker.service.ts
- packages/node/src/stellar/api.connection.spec.ts
- packages/node/src/stellar/api.service.stellar.ts
- packages/node/src/stellar/api.stellar.spec.ts
- packages/node/src/stellar/utils.stellar.ts
- packages/node/src/subcommands/testing.service.ts
- yarn.lock
Remove unused deps or deps that have moved to node core.
Remove deprecated type
> Clean up deps, remove deprecated types

- packages/node/CHANGELOG.md
- packages/node/package.json
- yarn.lock
> [release] 20240502-2

- packages/node/CHANGELOG.md
> [release] 20240502 patch 2

- packages/node/CHANGELOG.md
> [release] 20240503

- .github/workflows/node-docker.yml
> [SKIP CI] update build image

- .yarn/versions/25a81053.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
> [release] 20240703

- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/src/project/models.ts
- packages/node/CHANGELOG.md
Fix issue 
```
| 2024-08-15T06:38:57.411Z <configure> ERROR undefined Error: Invalid keys present in value: {"type":"payment"}. Whitelisted keys: ["type","sourceAccount"]
```
> Fix issue in OperationFilter

- .yarn/versions/9ee991a9.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
> [release] 20240821

- .yarn/versions/18d61b39.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
> [release] 20240827

- .yarn/versions/ec34fc3c.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
> [release] 20241022

- .yarn/versions/1d5be3a1.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
> [release] 20241022-3

- .yarn/versions/d5a8c016.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
> [release] 20241127

- .yarn/versions/3cd98ea0.yml
- .yarn/versions/5ec53f87.yml
- .yarnrc.yml
- packages/common-stellar/CHANGELOG.md
- packages/common-stellar/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
> [release] 20241217

- packages/node/CHANGELOG.md
- packages/node/src/app.module.ts
This reverts commit 14c5d4125ea438cacabd9aa1f79331e229ede5af.
> Revert "Revert "fix module stellar-sdk not found""

- packages/node/CHANGELOG.md
- packages/node/package.json
> [release] 20150115

- .yarn/versions/f073b19c.yml
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/node/src/stellar/soroban.server.spec.ts
- packages/types/CHANGELOG.md
- packages/types/package.json
> [release] 20250226

- packages/node/CHANGELOG.md
- packages/node/src/indexer/indexer.manager.ts
- packages/node/src/stellar/api.stellar.ts
Fixes identifying the operation for effects as well as improving iterating operations, effects and events.
> Fix associating effects to operations
